### ISSUE TITLE
Incomplete CORS/OPTIONS responses when two identical URIs are registered

### ISSUE THREAD

**Issue by timjstewart** [RestExpress/PluginExpress#15]
Here is some code that exhibits the error (this is a method from a controller):

    public void registerRoutes(final RestExpress restExpress) {
       Objects.requireNonNull(restExpress, "restExpress cannot be null");

       final String collectiveRoute = "/codes.{format}";
       final String singleRoute     = "/codes/{codeId}.{format}";

       restExpress.uri(collectiveRoute, this)
          .action("createCode", HttpMethod.POST)
          .name("createCode");

       restExpress.uri(collectiveRoute, this)
          .action("listCodes", HttpMethod.GET)
          .name("listCodes");

       restExpress.uri(singleRoute, this)
          .action("deleteCode", HttpMethod.DELETE)
          .name("deleteCode");

       restExpress.uri(singleRoute, this)
          .action("getCode", HttpMethod.GET)
          .name("getCode");

       restExpress.uri(singleRoute, this)
          .action("updateCode", HttpMethod.PUT)
          .name("updateCode");
     }

With this code, performing an OPTIONS request against one of the routes returns only two methods: OPTIONS and one other method.

I believe it's because I've created multiple route builders that have the same URI and the following code in CorsHeaderPlugin.register():

	methodsByPattern.put(pathPattern, methods);

overwrites the previously inserted value for the pathPattern key.

To make this clearer, I remember seeing the following calls:

	methodsByPattern.put("/code", { OPTIONS, GET });
	methodsByPattern.put("/code", { OPTIONS, PUT });
	methodsByPattern.put("/code", { OPTIONS, DELETE });

The last one wins.  Perhaps merging the methods in the map's value would be a good approach.

The workaround I found is to do the following:

    public void registerRoutes(final RestExpress restExpress) {
        Objects.requireNonNull(restExpress, "restExpress cannot be null");

        final String collectiveRoute = "/codes.{format}";
        final String singleRoute     = "/codes/{codeId}.{format}";

        restExpress.uri(collectiveRoute, this)
                .action("createCode", HttpMethod.POST)
                .action("listCodes", HttpMethod.GET)
                .name("codes");

        restExpress.uri(singleRoute, this)
                .action("deleteCode", HttpMethod.DELETE)
                .action("updateCode", HttpMethod.PUT)
                .action("getCode", HttpMethod.GET)
                .name("code");
    }

Now there is only one RouteBuilder per URI so the methodsByPattern map will never have the same key inserted twice.

If you think my approach of merging methods is the best way to go, I'd be happy to submit a pull request with those changes in it.

**Comment by tfredrich** [comment]
Sounds good, Tim. Fire up a pull request whenever!

**Comment by tfredrich** [comment]
Certainly RestExpress was written with the "workaround" path in mind... that a route is a URL that can support multiple HTTP methods. Wondering if we "fix" this or make it throw an exception--to be opinionated?

**Comment by tfredrich** [comment]
Evidently, this was inadvertently fixed in 0.2.2! New test in 0.3.3-SNAPSHOT confirms.
