### ISSUE TITLE
Update Swagger Plugin to 2.0

### ISSUE THREAD

**Issue by cblaze22** [RestExpress/PluginExpress#25]
I am not sure how much different 1.2 and 2.0 of Swagger is, but can the existing Swagger plugin be upgraded to 2.0 easily, or does this involve a complete overhaul.  Trying to see how much work that is.

**Comment by tfredrich** [comment]
This may help when analyzing the deltas: https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide

**Comment by tfredrich** [comment]
Vlad Pop may get to this in December. See: https://groups.google.com/forum/#!topic/restexpress/EeKssXnilk4
