### ISSUE TITLE
suggestion of replacing white space on nickname

### ISSUE THREAD

**Issue by gayanscorpio** [RestExpress/PluginExpress#30]
According to Swagger RESTful API Documentation Specification, (refer : https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md) the nickname MUST be alphanumeric and may include underscores ,Whitespace characters are not allowed.

/swagger/src/main/java/com/strategicgains/restexpress/plugin/swagger/domain/ApiOperation.java :

this.nickname = method + (name == null ? "" : " " + name);

My suggestion is to replace the white space with "_".

If you think my suggestion of replacing white space is the best way to go, I'd be happy to submit a pull request with those changes in it.

**Comment by tfredrich** [comment]
Thank you for your suggestion. I'm happy to take a pull request for this feature.

**Comment by tfredrich** [comment]
Removed the injection of the blank (whitespace) altogether, to maintain the current contract.

Available in 0.3.1-SNAPSHOT
